name: Pull_Request_Tests

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MIDDLE_END_URL: ${{ secrets.MIDDLE_END_URL }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'run yarn'
        run: |
          yarn install
          yarn run lint
          yarn run build
          yarn run test:e2e:ci
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
