name: Pull_Request_Tests

on:
  pull_request:
    branches:
    - master
    - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        MIDDLE_END_URL: ${{ secrets.MIDDLE_END_URL }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'run npm'
      run: |
        npm install
        npm run lint --if-present
        npm run build --if-present
        npm run test --if-present
